<?php
include_once('ons_common.php');

class ClassTest extends DataBaseTables
{
	public $tables=array("Class");
	
	function DataRowProvider(){
		return array(
			array(1,array("Name"=>"Sweet Peas","Description"=>"3 x one cultivars")),
			array(2,array("Name"=>"Sweet Peas","Description"=>"6 x two or more cultivars")),
			array(3,array("Name"=>"Pansies","Description"=>"4 blooms")),
			array(4,array("Name"=>"Pinks","Description"=>"4 blooms")),
			array(5,array("Name"=>"Small Flowers","Description"=>"6 blooms (not to sxceed size of ?2 coin)")),
			array(6,array("Name"=>"Clematis","Description"=>"one bloom")),
			array(7,array("Name"=>"Clematis","Description"=>"3 blooms")),
			array(8,array("Name"=>"Roses","Description"=>"3 blooms H.T. of one cultivar")),
			array(9,array("Name"=>"Roses","Description"=>"3 blooms H.T. of two or more cultivars")),
			array(10,array("Name"=>"Roses","Description"=>"3 stems floribunda type")),
/** /				
			array(11,array("Name"=>"Roses","Description"=>"one specimen type")),
			array(12,array("Name"=>"A vase of annuals","Description"=>"not to exceed 9 stems")),
			array(13,array("Name"=>"A vase of any other flowers","Description"=>"not to exceed 9 stems")),
			array(14,array("Name"=>"3 stems Penstemons","Description"=>"any variety")),
			array(15,array("Name"=>"Flowering Shrub(s)","Description"=>"vase of 3 stems")),
			array(16,array("Name"=>"Dahlia","Description"=>"vase of 1 stem")),
			array(17,array("Name"=>"Fuchsias","Description"=>"1 trailing any size pot")),
			array(18,array("Name"=>"Fuchsias","Description"=>"1 double any size pot")),
			array(19,array("Name"=>"Fuchsias","Description"=>"1 bush/shrub type pot max 8\"/20cm")),
			array(20,array("Name"=>"Fuchsias","Description"=>"1 bush/shrub type pot max 6\"/15cm")),
			array(21,array("Name"=>"Patio Pot","Description"=>"12\"/30cm across; any type; any shape")),
			array(22,array("Name"=>"Begonias","Description"=>"1 any size pot")),
			array(23,array("Name"=>"Regal Pelargonium","Description"=>"1 any size pot")),
			array(24,array("Name"=>"Geranium","Description"=>"1 any size pot")),
			array(25,array("Name"=>"Flowering Plant","Description"=>"1 any size pot (not in own class)")),
			array(26,array("Name"=>"Foliage Plant","Description"=>"1 any size pot")),
			array(27,array("Name"=>"Succulents or cacti","Description"=>"in any size pot")),
			array(28,array("Name"=>"Broad Beans","Description"=>"6 pods")),
			array(29,array("Name"=>"Dwarf Beans","Description"=>"6 pods")),
			array(30,array("Name"=>"Beetroot","Description"=>"3")),
			array(31,array("Name"=>"Cabbages (pointed or round)","Description"=>"2 x 2/4\" stalk (5/10cm)")),
			array(32,array("Name"=>"Radishes","Description"=>"5 untrimmed")),
			array(33,array("Name"=>"Carrots (stump rooted)","Description"=>"5")),
			array(34,array("Name"=>"Carrots (long)","Description"=>"5")),
			array(35,array("Name"=>"Courgette","Description"=>"2")),
			array(36,array("Name"=>"Lettuce (cabbage)","Description"=>"2")),
			array(37,array("Name"=>"Lettuce (other)","Description"=>"2")),
			array(38,array("Name"=>"Spring Onions","Description"=>"6 untrimmed")),
			array(39,array("Name"=>"Onions (grown from sets)","Description"=>"6")),
			array(40,array("Name"=>"Peas","Description"=>"6 pods")),
			array(41,array("Name"=>"Potatoes","Description"=>"5 of any variety")),
			array(42,array("Name"=>"Shallots (under 30mm)","Description"=>"9")),
			array(43,array("Name"=>"Shallots (over 30mm)","Description"=>"9")),
			array(44,array("Name"=>"Any other vegetable","Description"=>"2")),
			array(45,array("Name"=>"Rhubarb","Description"=>"5 sticks minus leaves")),
			array(46,array("Name"=>"Tomatoes","Description"=>"3 with calyx")),
			array(47,array("Name"=>"Any Herb","Description"=>"in pot max size 5\"")),
			array(48,array("Name"=>"1 Vegetable and 1 Flower")),
			array(49,array("Name"=>"Two different fresh culinary herbs","Description"=>"1 vase max 3\"/7.5cm diam")),
			array(50,array("Name"=>"Black currants","Description"=>"3 strings")),
			array(51,array("Name"=>"Redcurrants","Description"=>"3 strings")),
			array(52,array("Name"=>"Raspberries","Description"=>"6 with calyx")),
			array(53,array("Name"=>"Strawberries","Description"=>"6 with calyx")),
			array(54,array("Name"=>"Any other fruit","Description"=>"5")),
			array(55,array("Name"=>"\"Garden Party\"","Description"=>"a floral exhibit")),
			array(56,array("Name"=>"A Walk by the River","Description"=>"an exhibit using flowers and/or foliage")),
			array(57,array("Name"=>"Display In A Watering Can","Description"=>"a floral/foliage exhibit")),
			array(58,array("Name"=>"1 Jar Jam","Description"=>"1lb/500g jar as specified")),
			array(59,array("Name"=>"Biscuits","Description"=>"5")),
			array(60,array("Name"=>"Scones (plain)","Description"=>"5")),
			array(61,array("Name"=>"Victoria Jam Sandwich","Description"=>"7.5\"/18cm diameter approx")),
			array(62,array("Name"=>"1 Apple Plate Pie","Description"=>"not exceeding 9\"/23cm")),
			array(63,array("Name"=>"1 Fruit Cake (Any Shape)","Description"=>"not exceeding 9\"/23cm")),
			array(64,array("Name"=>"1 Savoury Quiche or Flan","Description"=>"up to 8\"/20cm diameter")),
			array(65,array("Name"=>"Water")),
			array(66,array("Name"=>"Flowers")),
			array(67,array("Name"=>"Young Animals or Birds","Description"=>"eg. puppies, kittens")),
			array(68,array("Name"=>"Winter Scene")),
			array(69,array("Name"=>"Cross stich/canvas work","Description"=>"framed or unframed")),
			array(70,array("Name"=>"Embroidery/lace","Description"=>"Max size overall 24\"/60cm x18\"/45cm")),
			array(71,array("Name"=>"Knitting/crochet","Description"=>"state if own design")),
			array(72,array("Name"=>"Still Life","Description"=>"Any Medium")),
			array(73,array("Name"=>"A Figure","Description"=>"Any Medium")),
			array(74,array("Name"=>"A Landscape","Description"=>"Any Medium")),
			array(75,array("Name"=>"Any Subject","Description"=>"Any Medium")),
			array(76,array("Name"=>"Hobby Exhibit","Description"=>"not included in any other class")),
			array(77,array("Name"=>"Greetings Card","Description"=>"Max Size A5")),
			array(78,array("Name"=>"A Collage","Description"=>"Age 3-6 Max Size A4")),
			array(79,array("Name"=>"A Garden in a Seed Tray","Description"=>"Age 7-11 Max size 38x23cm")),
			array(80,array("Name"=>"Greetings Card","Description"=>"Age 3-6 Max Size A5")),
			array(81,array("Name"=>"Greetings Card","Description"=>"Age 7-11 Max Size A5")),
			array(82,array("Name"=>"A Fruit and/or Vegetable Monster","Description"=>"Age 3-6")),
			array(83,array("Name"=>"A Fruit and/or Vegetable Monster","Description"=>"Age 7-11")),
			array(84,array("Name"=>"Painted Stone","Description"=>"Age 3-6")),
			array(85,array("Name"=>"A Small Vase of Flowers","Description"=>"Age 7-11")),
			array(86,array("Name"=>"Embroidery/Needlework/Textiles","Description"=>"Age 7-11")),
			array(87,array("Name"=>"Hanging basket","Description"=>"(max size 12\"/30cm wire or plastic)")),
			array(88,array("Name"=>"\"Football World Cup\"","Description"=>"a floral exhibit")),
			array(89,array("Name"=>"Monochrome","Description"=>"exhibit using flowers of one colour")),
			array(90,array("Name"=>"Floating Heads","Description"=>"a floral exhibit")),
			array(91,array("Name"=>"Transport")),
			array(92,array("Name"=>"Textures")),
			array(93,array("Name"=>"Fun in the Snow")),
			array(94,array("Name"=>"Trees/Shrubs in Flower")),
			array(95,array("Name"=>"Finger Puppet")),
			array(96,array("Name"=>"Finger Puppet","Description"=>"Age 3-6")),
			array(97,array("Name"=>"3 Trumpet Daffs - Yellow")),
			array(98,array("Name"=>"3 Trumpet Daffs - White")),
			array(99,array("Name"=>"3 Large Cup Narc - Yellow")),
			array(100,array("Name"=>"3 Large Cup Narc - White")),
			array(101,array("Name"=>"3 Large Cup Narc - 2+ Variety")),
			array(102,array("Name"=>"3 Small Cup Narc")),
			array(103,array("Name"=>"3 Double Daffs")),
			array(104,array("Name"=>"3 Daffs - Single Head")),
			array(105,array("Name"=>"3 Daffs - Multi Head")),
			array(106,array("Name"=>"1 Trumpet Daff - Yellow")),
			array(107,array("Name"=>"1 Trumpet Daff - White")),
			array(108,array("Name"=>"1 Large Cup Narc - Yellow")),
			array(109,array("Name"=>"1 Large Cup Narc - White")),
			array(110,array("Name"=>"1 Small Cup Narc ")),
			array(111,array("Name"=>"1 Double Daff")),
			array(112,array("Name"=>"1 Triandrus")),
			array(113,array("Name"=>"1 Cyclamineous Narc")),
			array(114,array("Name"=>"1 Single Headed")),
			array(115,array("Name"=>"1 Multi Headed")),
			array(116,array("Name"=>"Society Bulb")),
			array(117,array("Name"=>"3 Tulips")),
			array(118,array("Name"=>"3 Polyanthus")),
			array(119,array("Name"=>"6 Pansies/Violas")),
			array(120,array("Name"=>"Spring Flowers")),
			array(121,array("Name"=>"3 Flowering Shrubs")),
			array(122,array("Name"=>"Pot Daffs/Narc")),
			array(123,array("Name"=>"Pot Any Bulb")),
			array(124,array("Name"=>"Amaryllis")),
			array(125,array("Name"=>"Pot Primula")),
			array(126,array("Name"=>"Pot Foliage")),
			array(127,array("Name"=>"Any Other Pot")),
			array(128,array("Name"=>"Pot Succulents/Cacti")),
			array(129,array("Name"=>"Arrangement")),
			array(130,array("Name"=>"Vase of annuals")),
			array(131,array("Name"=>"Vase of any other flowers")),
			array(132,array("Name"=>"Floral Greeting Card 3/6")),
			array(133,array("Name"=>"Decorated Plant Pot")),
			array(134,array("Name"=>"Decorated Wooden Spoon")),
			array(135,array("Name"=>"Decorated Plant Pot 3/6")),
			array(136,array("Name"=>"Garden in a Seed Tray 7/11")),
			array(137,array("Name"=>"Floral Greetings Card 7/11")),
			array(138,array("Name"=>"Decorated Plant Pot 7/11")),
			array(139,array("Name"=>"Small Vase of Flowers 7/11")),
			array(140,array("Name"=>"Photo of my Pet")),
			array(141,array("Name"=>"Carrots (stump rooted) 3")),
			array(142,array("Name"=>"Canvas Work")),
			array(143,array("Name"=>"Cross Stitch")),
			array(144,array("Name"=>"Lace")),
			array(145,array("Name"=>"Knitting")),
			array(146,array("Name"=>"Crochet")),
			array(147,array("Name"=>"Gooseberries")),
			array(148,array("Name"=>"Somewhere over the rainbow")),
			array(149,array("Name"=>"Miniature")),
			array(150,array("Name"=>"Jar Jam")),
			array(151,array("Name"=>"Cup Cakes")),
			array(152,array("Name"=>"Apple Plate Pie")),
			array(153,array("Name"=>"Fruit Cake")),
			array(154,array("Name"=>"Savoury Quiche")),
			array(155,array("Name"=>"Airborne")),
			array(156,array("Name"=>"BHS Outings")),
			array(157,array("Name"=>"Favourite Flower")),
			array(158,array("Name"=>"Winter Colour in the Garden")),
			array(159,array("Name"=>"3 Red Tulips")),
			array(160,array("Name"=>"3 Yellow Tulips")),
			array(161,array("Name"=>"Hyacinths")),
			array(162,array("Name"=>"Irises")),
			array(163,array("Name"=>"Pot Alpine")),
			array(164,array("Name"=>"Garden Flower Arrangement")),
/**/			
		);
	}

	function FileName(){
		return "Tables/Class";
	}	
}
?>