<?php
include_once('ons_common.php');

class ExhibitorTest extends DataBaseTables
{
	public $tables=array("Exhibitor");
	
	function DataRowProvider(){
		return array(
			array(1,array("Surname"=>"George","Member"=>0,"Title"=>"Mr","Initials"=>"P")),
			array(2,array("Surname"=>"Payne","Member"=>0,"Title"=>"Mrs","Initials"=>"S M")),
			array(3,array("Surname"=>"Clarke","Member"=>0,"Title"=>"Mrs",)),
			array(4,array("Surname"=>"Lee","Member"=>0,"Title"=>"Mrs",)),
			array(5,array("Surname"=>"Davey","Member"=>0,"Title"=>"Mrs",)),
			array(6,array("Surname"=>"Metcalfe","Member"=>1,"Title"=>"Mrs","Initials"=>"E")),
			array(7,array("Surname"=>"Metcalfe","Member"=>0,"Title"=>"Mr","Initials"=>"A J")),
			array(8,array("Surname"=>"Bird","Member"=>0,"Title"=>"Mr","Initials"=>"J")),
			array(9,array("Surname"=>"Wagstaff","Member"=>0,"Title"=>"Mrs",)),
			array(10,array("Surname"=>"Ginn","Member"=>0,"Title"=>"Mr",)),
/** /				
			array(11,array("Surname"=>"West","Member"=>0,"Title"=>"Mrs",)),
			array(12,array("Surname"=>"Fairey","Member"=>0,"Title"=>"Mr","Initials"=>"B")),
			array(13,array("Surname"=>"Fairey","Member"=>0,"Title"=>"Mrs","Initials"=>"E R")),
			array(14,array("Surname"=>"Davidson","Member"=>0,"Title"=>"Mrs","Initials"=>"J")),
			array(15,array("Surname"=>"Dashwood","Member"=>0,"Title"=>"Mrs","Initials"=>"B")),
			array(16,array("Surname"=>"Mynott","Member"=>0,"Title"=>"Mr",)),
			array(17,array("Surname"=>"Davidson","Member"=>0,"Title"=>"Mr","Initials"=>"H")),
			array(18,array("Surname"=>"Harris","Member"=>1,"Title"=>"Mrs","Initials"=>"P")),
			array(19,array("Surname"=>"Harris","Member"=>1,"Title"=>"Mr","Initials"=>"D")),
			array(20,array("Surname"=>"Gray","Member"=>1,"Title"=>"Mrs","Initials"=>"P")),
			array(21,array("Surname"=>"Kuzminski","Member"=>1,"Title"=>"Mrs","Initials"=>"E")),
			array(22,array("Surname"=>"Clark","Member"=>1,"Title"=>"Mrs","Initials"=>"S")),
			array(23,array("Surname"=>"Kuzminski","Member"=>1,"Title"=>"Mr","Initials"=>"A")),
			array(24,array("Surname"=>"Livermore","Member"=>0,"Title"=>"Mrs","Initials"=>"E")),
			array(25,array("Surname"=>"Char","Member"=>0,)),
			array(26,array("Surname"=>"Livermore","Member"=>0,"Title"=>"Mr","Initials"=>"D")),
			array(27,array("Surname"=>"Char","Member"=>0,)),
			array(28,array("Surname"=>"Hurren","Member"=>0,"Title"=>"Mr","Initials"=>"P")),
			array(29,array("Surname"=>"Livermore","Member"=>0,"Title"=>"Mrs",)),
			array(30,array("Surname"=>"Thomas","Member"=>0,"Title"=>"Mrs","Initials"=>"J")),
			array(31,array("Surname"=>"Campbell","Member"=>1,"Title"=>"Mrs","Initials"=>"J")),
			array(32,array("Surname"=>"Driver","Member"=>0,"Title"=>"Mrs","Initials"=>"V")),
			array(33,array("Surname"=>"Watson","Member"=>0,"Title"=>"Mrs","Initials"=>"J")),
			array(34,array("Surname"=>"Gray","Member"=>1,"Title"=>"Mr","Initials"=>"J")),
			array(35,array("Surname"=>"Potts","Member"=>0,"Title"=>"Mrs","Initials"=>"F")),
			array(36,array("Surname"=>"Scott","Member"=>0,"Title"=>"Mrs","Initials"=>"J E")),
			array(37,array("Surname"=>"Scott","Member"=>0,"Title"=>"Mr",)),
			array(38,array("Surname"=>"Chalkley","Member"=>0,"Title"=>"Mrs","Initials"=>"P")),
			array(39,array("Surname"=>"Brierley","Member"=>0,"Title"=>"Mr",)),
			array(40,array("Surname"=>"Cannon","Member"=>0,"Title"=>"Mrs",)),
			array(41,array("Surname"=>"Beatie","Member"=>0,"Initials"=>"J")),
			array(42,array("Surname"=>"Southwood","Member"=>0,"Initials"=>"J")),
			array(43,array("Surname"=>"Ball","Member"=>1,"Title"=>"Mrs",)),
			array(44,array("Surname"=>"Filby","Member"=>1,"Title"=>"Mrs","Initials"=>"A")),
			array(45,array("Surname"=>"Filby","Member"=>1,"Title"=>"Mr",)),
			array(46,array("Surname"=>"Camp","Member"=>0,"Initials"=>"M")),
			array(47,array("Surname"=>"Palfreyman","Member"=>0,"Title"=>"Mrs","Initials"=>"J")),
			array(48,array("Surname"=>"Camp","Member"=>0,"Title"=>"Mrs","Initials"=>"A")),
			array(49,array("Surname"=>"Hailey","Member"=>0,"Title"=>"Mrs",)),
			array(50,array("Surname"=>"Palfreyman","Member"=>0,"Title"=>"Mrs",)),
			array(51,array("Surname"=>"Gammon","Member"=>0,"Title"=>"Mrs","Initials"=>"C R")),
			array(52,array("Surname"=>"Rusted","Member"=>0,"Title"=>"Mrs","Initials"=>"S")),
			array(53,array("Surname"=>"Palfreyman","Member"=>0,"Title"=>"Mr",)),
			array(54,array("Surname"=>"Campbell","Member"=>0,"Initials"=>"Annabelle")),
			array(55,array("Surname"=>"Goddard","Member"=>0,"Initials"=>"Lotte")),
			array(56,array("Surname"=>"Groves","Member"=>0,"Initials"=>"Maddy")),
			array(57,array("Surname"=>"Hughes","Member"=>0,"Initials"=>"Emily")),
			array(58,array("Surname"=>"Knight","Member"=>0,"Initials"=>"Amber")),
			array(59,array("Surname"=>"Knight","Member"=>0,"Initials"=>"Jasmine")),
			array(60,array("Surname"=>"Mills","Member"=>0,"Initials"=>"Eleanor")),
			array(61,array("Surname"=>"Lucas","Member"=>0,"Initials"=>"Zoe")),
			array(62,array("Surname"=>"Pearce","Member"=>0,"Initials"=>"Lucy")),
			array(63,array("Surname"=>"Prior","Member"=>0,"Initials"=>"Sophie")),
			array(64,array("Surname"=>"Sell","Member"=>0,"Initials"=>"Bethany")),
			array(65,array("Surname"=>"Whinray-Edwards","Member"=>0,"Initials"=>"Robyn")),
			array(66,array("Surname"=>"Wilcox","Member"=>0,"Initials"=>"Ellie")),
			array(67,array("Surname"=>"Wilcox","Member"=>0,"Initials"=>"Neave")),
			array(68,array("Surname"=>"Stokes","Member"=>0,"Initials"=>"Jade")),
			array(69,array("Surname"=>"Isabelle","Member"=>0,)),
			array(70,array("Surname"=>"Bailey","Member"=>0,)),
			array(71,array("Surname"=>"Darragh","Member"=>0,)),
			array(72,array("Surname"=>"Elle-May","Member"=>0,)),
			array(73,array("Surname"=>"Amy","Member"=>0,)),
			array(74,array("Surname"=>"Beth","Member"=>0,)),
			array(75,array("Surname"=>"Amelia","Member"=>0,)),
			array(76,array("Surname"=>"Matilda","Member"=>0,)),
			array(77,array("Surname"=>"Rio","Member"=>0,)),
			array(78,array("Surname"=>"Ella","Member"=>0,)),
			array(79,array("Surname"=>"Jake","Member"=>0,)),
			array(80,array("Surname"=>"Jack","Member"=>0,)),
			array(81,array("Surname"=>"Gabriella","Member"=>0,)),
			array(82,array("Surname"=>"Raphael","Member"=>0,)),
			array(83,array("Surname"=>"Owen","Member"=>0,)),
			array(84,array("Surname"=>"Raphael","Member"=>0,)),
			array(85,array("Surname"=>"Rhys","Member"=>0,)),
			array(86,array("Surname"=>"Summer","Member"=>0,)),
			array(87,array("Surname"=>"Jarral","Member"=>0,"Initials"=>"Z")),
			array(88,array("Surname"=>"Charsley","Member"=>0,"Initials"=>"R")),
			array(89,array("Surname"=>"Charsley","Member"=>0,"Initials"=>"R")),
			array(90,array("Surname"=>"Charsley","Member"=>0,"Initials"=>"N")),
			array(91,array("Surname"=>"Gray","Member"=>0,"Initials"=>"Pat")),
			array(92,array("Surname"=>"Harris","Member"=>0,"Initials"=>"Pam")),
			array(93,array("Surname"=>"Charsley","Member"=>0,"Initials"=>"Rosemary")),
			array(94,array("Surname"=>"Metcalfe","Member"=>0,"Initials"=>"Eunice")),
			array(95,array("Surname"=>"Harris","Member"=>0,"Initials"=>"Don")),
			array(96,array("Surname"=>"Smith","Member"=>0,"Initials"=>"Iris")),
			array(97,array("Surname"=>"Turner","Member"=>0,"Initials"=>"Chris")),
			array(98,array("Surname"=>"Kuzminski","Member"=>0,"Initials"=>"Adam")),
			array(99,array("Surname"=>"UNKNOWN","Member"=>0,)),
			array(100,array("Surname"=>"Camp","Member"=>1,"Initials"=>"Mick")),
			array(101,array("Surname"=>"Willans","Member"=>0,"Initials"=>"Thelma")),
			array(102,array("Surname"=>"Kuzminski","Member"=>0,"Initials"=>"Liz")),
			array(103,array("Surname"=>"Page","Member"=>0,"Initials"=>"Mary")),
			array(104,array("Surname"=>"Camp","Member"=>0,"Initials"=>"Angela")),
			array(105,array("Surname"=>"Wagstaff","Member"=>1,"Initials"=>"Vera")),
			array(106,array("Surname"=>"Ephgrave","Member"=>1,"Initials"=>"Barbara")),
			array(107,array("Surname"=>"Ephgrave","Member"=>0,"Initials"=>"Martin")),
			array(108,array("Surname"=>"Collins","Member"=>0,"Initials"=>"Bobbie")),
			array(109,array("Surname"=>"Luker","Member"=>0,"Initials"=>"Martin")),
			array(110,array("Surname"=>"Luker","Member"=>0,"Initials"=>"Angela")),
			array(111,array("Surname"=>"Barker","Member"=>0,"Initials"=>"Carol")),
			array(112,array("Surname"=>"Robinson","Member"=>0,"Initials"=>"Pat")),
			array(113,array("Surname"=>"Furze","Member"=>0,"Initials"=>"Helen")),
			array(114,array("Surname"=>"Gates","Member"=>0,"Initials"=>"Shirley")),
			array(115,array("Surname"=>"Harnden","Member"=>0,"Initials"=>"Monica")),
			array(116,array("Surname"=>"Hamblin","Member"=>0,"Initials"=>"Shirley")),
			array(117,array("Surname"=>"Watson","Member"=>0,"Initials"=>"Jean")),
			array(118,array("Surname"=>"Kirke","Member"=>0,"Initials"=>"Maired")),
			array(119,array("Surname"=>"Scott","Member"=>0,"Initials"=>"Karen")),
			array(120,array("Surname"=>"Scott","Member"=>1,"Initials"=>"Arthur")),
			array(121,array("Surname"=>"Hayward","Member"=>0,"Initials"=>"Janet")),
			array(122,array("Surname"=>"Mills","Member"=>0,"Title"=>"Mr","Initials"=>"P M")),
			array(123,array("Surname"=>"Eley","Member"=>0,"Title"=>"Mrs","Initials"=>"D")),
			array(124,array("Surname"=>"Hoskins","Member"=>1,"Title"=>"Mrs","Initials"=>"J F E")),
			array(125,array("Surname"=>"Horley","Member"=>1,"Title"=>"Mrs","Initials"=>"S")),
			array(126,array("Surname"=>"Smart","Member"=>0,"Title"=>"Mr","Initials"=>"R T")),
			array(127,array("Surname"=>"Ginn","Member"=>0,"Title"=>"Mrs","Initials"=>"A")),
			array(128,array("Surname"=>"Saville","Member"=>0,"Title"=>"Mr","Initials"=>"D")),
			array(129,array("Surname"=>"Paxton","Member"=>0,"Title"=>"Mr","Initials"=>"Chris")),
			array(130,array("Surname"=>"Metcalfe","Member"=>0,"Title"=>"Mrs","Initials"=>"Ann")),
			array(131,array("Surname"=>"Clark","Member"=>0,"Title"=>"Mr","Initials"=>"P")),
			array(132,array("Surname"=>"Stokes","Member"=>0,"Initials"=>"Jade")),
			array(133,array("Surname"=>"Thomas","Member"=>0,"Initials"=>"Mary")),
			array(134,array("Surname"=>"Over","Member"=>0,"Initials"=>"Francesca")),
			array(135,array("Surname"=>"Lewis","Member"=>0,"Initials"=>"Abi")),
			array(136,array("Surname"=>"Rashid","Member"=>0,"Initials"=>"Shakirah")),
			array(137,array("Surname"=>"Parkin","Member"=>0,"Initials"=>"Lola")),
			array(138,array("Surname"=>"Lalli","Member"=>0,"Initials"=>"Gursimran")),
			array(139,array("Surname"=>"Lalli","Member"=>0,"Initials"=>"Sukhmani")),
			array(140,array("Surname"=>"O'Connor","Member"=>0,"Initials"=>"Caitlin")),
			array(141,array("Surname"=>"Lucas","Member"=>0,"Initials"=>"Amy")),
			array(142,array("Surname"=>"Williams","Member"=>0,"Initials"=>"Joshua")),
			array(143,array("Surname"=>"Baxter","Member"=>0,"Initials"=>"Eden")),
			array(144,array("Surname"=>"Hand","Member"=>0,"Initials"=>"Rosie")),
			array(145,array("Surname"=>"Jones","Member"=>0,"Initials"=>"Bettsie")),
			array(146,array("Surname"=>"Wright","Member"=>0,"Initials"=>"Charlotte")),
			array(147,array("Surname"=>"MacDonald","Member"=>0,"Initials"=>"Samuel")),
			array(148,array("Surname"=>"Cotterell","Member"=>0,"Initials"=>"Millie")),
			array(149,array("Surname"=>"Bennet","Member"=>0,"Initials"=>"Xander")),
			array(150,array("Surname"=>"Gillham","Member"=>0,"Initials"=>"Anna")),
			array(151,array("Surname"=>"Rees","Member"=>0,"Initials"=>"Charlotte")),
			array(152,array("Surname"=>"Macheod","Member"=>0,"Initials"=>"Isla")),
			array(153,array("Surname"=>"Briffitt","Member"=>0,"Initials"=>"Sophie")),
			array(154,array("Surname"=>"Medland","Member"=>0,"Initials"=>"Casey")),
			array(155,array("Surname"=>"Catlin","Member"=>0,"Initials"=>"Harry")),
			array(156,array("Surname"=>"St Mary's","Member"=>0,"Initials"=>"Year 5")),
			array(157,array("Surname"=>"St Mary's","Member"=>0,"Initials"=>"Year 3")),
			array(158,array("Surname"=>"St Mary's","Member"=>0,"Initials"=>"Year 4")),
			array(159,array("Surname"=>"St Mary's","Member"=>0,"Initials"=>"Garden Club")),
			array(160,array("Surname"=>"Mills","Member"=>0,"Initials"=>"Luke")),
			array(161,array("Surname"=>"Collison","Member"=>0,"Initials"=>"Rebecca")),
			array(162,array("Surname"=>"Charsley","Member"=>0,"Title"=>"Mr","Initials"=>"N.A.")),
			array(163,array("Surname"=>"Hiorns","Member"=>1,"Title"=>"Mrs","Initials"=>"G")),
			array(164,array("Surname"=>"Keech","Member"=>1,"Title"=>"Mrs","Initials"=>"G")),
/**/								
		);
	}

	function FileName(){
		return "Tables/Exhibitor";
	}	
}
?>