<?php

if (!defined("__ONS_COMMON__"))
    include_once('ons_common.php');


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-19 at 22:27:47.
 */
class dbRootTest extends PHPUnit_Framework_TestCase {

    /**
     * @var dbRoot
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new dbRoot;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers dbRoot::clearCache
     * @todo   Implement testClearCache().
     */
    public function testClearCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::fromCache
     * @todo   Implement testFromCache().
     */
    public function testFromCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::Save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::updateDefaults
     * @todo   Implement testUpdateDefaults().
     */
    public function testUpdateDefaults() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::printForm
     * @todo   Implement testPrintForm().
     */
    public function testPrintForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::printList
     * @todo   Implement testPrintList().
     */
    public function testPrintList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::showPage
     * @todo   Implement testShowPage().
     */
    public function testShowPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::Fields2Backup
     * @todo   Implement testFields2Backup().
     */
    public function testFields2Backup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::BackupTable
     * @todo   Implement testBackupTable().
     */
    public function testBackupTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::getTables
     * @todo   Implement testGetTables().
     */
    public function testGetTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers dbRoot::BackupDB
     * @todo   Implement testBackupDB().
     */
    public function testBackupDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
