<?php

if (!defined("__ONS_COMMON__"))
    include_once('ons_common.php');


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-19 at 22:27:47.
 */
class dbRootTest extends PHPUnit_Framework_TestCase {

public $loadDB;

    function __construct($name = NULL, array $data = array(), $dataName = ''){
        error_log("Initialised ".get_class($this));
        $this->loadDB=new LoadDatabase("Functional/Cache",array("Defaults","Exhibition"));
        parent::__construct($name, $data , $dataName);
    }

    function testInitaliseDatabase(){
        $this->loadDB->testInitaliseDatabase();
    }
       
    /**
     * @covers dbRoot::fromCache
     * @todo   Implement testFromCache().
     */
    public function testFromCache() {
        global $dbTables;
        $defs=dbRoot::fromCache("Defaults",1);
        $this->assertGreaterThanOrEqual(1,count($dbTables["Defaults"]));
        $this->assertEquals("BHS",$defs->ShowName);
    }

    /**
     * @depends testFromCache
     */
    function testDefaultsCached(){
            $defs1=dbRoot::fromCache("Defaults",1);
            $defs2=dbRoot::fromCache("Defaults",1);

            $this->assertSame($defs1,$defs2);
    }

    
    /**
     * @covers dbRoot::clearCache
     * @depends testFromCache
     */
    public function testClearCache() {
        global $dbTables;
        dbRoot::clearCache("Defaults");
        $this->assertArrayNotHasKey("Defaults",$dbTables);
    }



    /**
     * @covers dbRoot::getTables
     * @todo   Implement testGetTables().
     */
    public function testGetTables() {
        $tables=dbRoot::getTables();
        //N.B. strtolower it so its consitent case.
        $tables=array_map('strtolower',$tables);
        //N.B. asort it so its alphabetical.        
        sort($tables);
        
        $this->assertEquals(
                array(
                    'class',
                    'defaultexhibitionclass',
                    'defaultexhibitionclassprize',
                    'defaultexhibitionexhibitor',
                    'defaultexhibitionsection',
                    'defaultexhibitiontrophyclass',
                    'defaultprizefund',
                    'defaults',
                    'exhibition',
                    'exhibitionclass',
                    'exhibitionclassprize',
                    'exhibitionexhibitor',
                    'exhibitionsection',
                    'exhibitiontrophyclass',
                    'exhibitor',
                    'prize',
                    'section',
                    'sponsorship',
                    'trophy',
                    'trophyresults')
                ,$tables);
    }

    /**
     * @covers dbRoot::BackupDB
     * @todo   Implement testBackupDB().
     */
    public function testBackupDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
