<?php
if (!defined("__ONS_COMMON__"))
    include_once('ons_common.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-20 at 09:00:01.
 */
class doDefaultExhibitionTrophyClassTest extends PHPUnit_Framework_TestCase {

    /**
     * @var doDefaultexhibitiontrophyclass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = safe_dataobject_factory('DefaultExhibitionTrophyClass');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers doDefaultexhibitiontrophyclass::keys
     * @todo   Implement testKeys().
     */
    public function testKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
