<?php

require_once 'ons_common.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-21 at 18:34:16.
 */
class doDefaultexhibitionclassTest extends DataBaseViews {

    /**
     * @covers doDefaultexhibitionclass::keys
     * @todo   Implement testKeys().
     */
    public function testKeys() {
        // Remove the following lines when you implement this test.
        $do = safe_dataobject_factory("Defaultexhibitionclass");
        $this->assertEquals(array("ID"), $do->keys());
    }

    public $tables = array("DefaultExhibitionClass");

    function DataRowProvider() {
        return array(
            array(1, array("ExhibitionClassID" => 97, "PrizeID" => 1, "Prize" => "1.50", "Points" => 15, "ExhibitionExhibitorID" => 33)),
            array(2, array("ExhibitionClassID" => 97, "PrizeID" => 2, "Prize" => "1.00", "Points" => 10, "ExhibitionExhibitorID" => 34)),
            array(3, array("ExhibitionClassID" => 1, "PrizeID" => 1, "Prize" => "1.50", "Points" => 15, "ExhibitionExhibitorID" => 1)),
            array(4, array("ExhibitionClassID" => 1, "PrizeID" => 2, "Prize" => "1.00", "Points" => 10, "ExhibitionExhibitorID" => 12)),
            array(5, array("ExhibitionClassID" => 1, "PrizeID" => 3, "Prize" => "0.50", "Points" => 5, "ExhibitionExhibitorID" => 15)),
            array(6, array("ExhibitionClassID" => 2, "PrizeID" => 1, "Prize" => "1.50", "Points" => 15, "ExhibitionExhibitorID" => 2)),
            array(7, array("ExhibitionClassID" => 2, "PrizeID" => 2, "Prize" => "1.00", "Points" => 10, "ExhibitionExhibitorID" => 14)),
            array(8, array("ExhibitionClassID" => 2, "PrizeID" => 3, "Prize" => "0.50", "Points" => 5, "ExhibitionExhibitorID" => 19)),
            array(9, array("ExhibitionClassID" => 3, "PrizeID" => 1, "Prize" => "1.50", "Points" => 15, "ExhibitionExhibitorID" => 3)),
            array(10, array("ExhibitionClassID" => 3, "PrizeID" => 2, "Prize" => "1.00", "Points" => 10, "ExhibitionExhibitorID" => 16)),
        );
    }

    function FileName() {
        return "Tables/DefaultExhibitionClass";
    }

}
