<?php

if (!defined("__ONS_COMMON__"))
    include_once('ons_common.php');
include_once 'results.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-20 at 09:27:34.
 */
class doResultsTest extends pagetests {

	public $tables=array("Defaults","Exhibition","ExhibitionExhibitor","Section","ExhibitionSection");
	
	function FileName(){
            return "ShowManager/Summer2013";
	}
	
	function getOutput(){            
            dbRoot::showPage("Results");		
	}

	public function ListProvider(){
            return array(
                array("<tr>\n<td>\nCompetitor 1: Mr P George</td>\n<td>\n<a class='Button' href='\?action=edit&id=1#form'><span>Edit</span></a>\n</td>\n</tr>"),
            );
        }

}
