<?php

if (!defined("__ONS_COMMON__"))
    include_once('ons_common.php');
include_once 'summary.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-20 at 09:27:37.
 */
class doSummaryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var doSummary
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new doSummary();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers doSummary::EditLink
     * @todo   Implement testEditLink().
     */
    public function testEditLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers doSummary::Name
     * @todo   Implement testName().
     */
    public function testName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
