-- --------------------------------------------------------

--
-- Table structure for table `class`
--

CREATE TABLE IF NOT EXISTS `class` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  `Description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Name` (`Name`,`Description`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

--
-- Dumping data for table `class`
--

INSERT INTO `class` (`ID`, `Name`, `Description`) VALUES
(88, '"Football World Cup"', 'a floral exhibit'),
(55, '"Garden Party"', 'a floral exhibit'),
(197, '"Fireworks"', 'an explosion of colour'),
(62, '1 Apple Plate Pie', 'not exceeding 9"/23cm'),
(113, '1 Cyclamineous Narc', NULL),
(111, '1 Double Daff', NULL),
(63, '1 Fruit Cake (Any Shape)', 'not exceeding 9"/23cm'),
(58, '1 Jar Jam', '1lb/500g jar as specified'),
(109, '1 Large Cup Narc - White', NULL),
(108, '1 Large Cup Narc - Yellow', NULL),
(115, '1 Multi Headed', NULL),
(64, '1 Savoury Quiche or Flan', 'up to 8"/20cm diameter'),
(114, '1 Single Headed', NULL),
(110, '1 Small Cup Narc ', NULL),
(112, '1 Triandrus', NULL),
(107, '1 Trumpet Daff - White', NULL),
(106, '1 Trumpet Daff - Yellow', NULL),
(48, '1 Vegetable and 1 Flower', NULL),
(105, '3 Daffs - Multi Head', NULL),
(104, '3 Daffs - Single Head', NULL),
(103, '3 Double Daffs', NULL),
(121, '3 Flowering Shrubs', NULL),
(101, '3 Large Cup Narc - 2+ Variety', NULL),
(100, '3 Large Cup Narc - White', NULL),
(99, '3 Large Cup Narc - Yellow', NULL),
(118, '3 Polyanthus', NULL),
(159, '3 Red Tulips', NULL),
(102, '3 Small Cup Narc', NULL),
(14, '3 stems Penstemons', 'any variety'),
(98, '3 Trumpet Daffs - White', NULL),
(97, '3 Trumpet Daffs - Yellow', NULL),
(117, '3 Tulips', NULL),
(160, '3 Yellow Tulips', NULL),
(119, '6 Pansies/Violas', NULL),
(78, 'A Collage', 'Age 3-6 Max Size A4'),
(73, 'A Figure', 'Any Medium'),
(82, 'A Fruit and/or Vegetable Monster', 'Age 3-6'),
(83, 'A Fruit and/or Vegetable Monster', 'Age 7-11'),
(79, 'A Garden in a Seed Tray', 'Age 7-11 Max size 38x23cm'),
(213, 'A Garden in a Seed Tray', 'Max size 38x23cm/15"x9"'),
(74, 'A Landscape', 'Any Medium'),
(85, 'A Small Vase of Flowers', 'Age 7-11'),
(12, 'A vase of annuals', 'not to exceed 9 stems'),
(13, 'A vase of any other flowers', 'not to exceed 9 stems'),
(56, 'A Walk by the River', 'an exhibit using flowers and/or foliage'),
(171, 'A Year in the Veg Garden', NULL),
(155, 'Airborne', NULL),
(124, 'Amaryllis', NULL),
(47, 'Any Herb', 'in pot max size 5"'),
-- (194, 'Any Herb', 'in pot max size 5"'),
(54, 'Any other fruit', '5'),
(127, 'Any Other Pot', NULL),
(44, 'Any other vegetable', '2'),
(221, 'Any Other Vegtable', '2'),
(75, 'Any Subject', 'Any Medium'),
(182, 'Any vegtable', NULL),
(152, 'Apple Plate Pie', NULL),
(202, 'Apple Plate Pie', 'not exceeding 9"/23cm'),
(129, 'Arrangement', NULL),
(199, 'Arrangement in a Wine Glass', NULL),
(170, 'Autumn Colour', NULL),
(209, 'Baldock Horticultural Society Outings 2012/2013', NULL),
(30, 'Beetroot', '3'),
(222, 'Beetroots', '3 trimmed to 7.5cm/3"'),
(22, 'Begonias', '1 any size pot'),
(190, 'Begonias (corm)', '1 any size pot'),
(156, 'BHS Outings', NULL),
(59, 'Biscuits', '5'),
(50, 'Black currants', '3 strings'),
(219, 'Broad Beans', '3 pods'),
(28, 'Broad Beans', '6 pods'),
(176, 'Broad Beans 3', NULL),
(180, 'Broad Beans 3 (3-6y)', NULL),
(31, 'Cabbages (pointed or round)', '2 x 2/4" stalk (5/10cm)'),
-- (193, 'Cabbages (pointed or round)', '2 x 2/4" stalk (5/10cm)'),
(142, 'Canvas Work', NULL),
(223, 'Carrots', '3 trimmed to 7.5cm/3"'),
(34, 'Carrots (long)', '5'),
(33, 'Carrots (stump rooted)', '5'),
(141, 'Carrots (stump rooted) 3', NULL),
(185, 'Clematis', '1 bloom'),
(7, 'Clematis', '3 blooms'),
(6, 'Clematis', 'one bloom'),
(215, 'Collage', 'Max Size A5'),
(173, 'Collage Max A5', NULL),
(35, 'Courgette', '2'),
(146, 'Crochet', NULL),
(69, 'Cross stich/canvas work', 'framed or unframed'),
(143, 'Cross Stitch', NULL),
(169, 'Cup and Saucer', NULL),
(151, 'Cup Cakes', NULL),
(16, 'Dahlia', 'vase of 1 stem'),
(179, 'Decorated Face Mask', NULL),
(133, 'Decorated Plant Pot', NULL),
(135, 'Decorated Plant Pot 3/6', NULL),
(138, 'Decorated Plant Pot 7/11', NULL),
(174, 'Decorated Small Cakes', NULL),
(216, 'Decorated Small Cakes', '4 (in cases)'),
(134, 'Decorated Wooden Spoon', NULL),
(57, 'Display In A Watering Can', 'a floral/foliage exhibit'),
(29, 'Dwarf Beans', '6 pods'),
(212, 'Embroidery', NULL),
(70, 'Embroidery/lace', 'Max size overall 24"/60cm x18"/45cm'),
(86, 'Embroidery/Needlework/Textiles', 'Age 7-11'),
(205, 'Fairy Cakes', '5 with a dusting of sugar'),
(166, 'Fairy Cakes 5', NULL),
(157, 'Favourite Flower', NULL),
(95, 'Finger Puppet', NULL),
(96, 'Finger Puppet', 'Age 3-6'),
(90, 'Floating Heads', 'a floral exhibit'),
(132, 'Floral Greeting Card 3/6', NULL),
(137, 'Floral Greetings Card 7/11', NULL),
(230, 'Floral Tribute', NULL),
(231, 'Floral Tribute', NULL),
(25, 'Flowering Plant', '1 any size pot (not in own class)'),
(191, 'Flowering Plant (not in own class)', '1 any size pot'),
(15, 'Flowering Shrub(s)', 'vase of 3 stems'),
(66, 'Flowers', NULL),
(26, 'Foliage Plant', '1 any size pot'),
(153, 'Fruit Cake', NULL),
(203, 'Fruit Cake (Any Shape)', 'not exceeding 9"/23cm'),
(20, 'Fuchsias', '1 bush/shrub type pot max 6"/15cm'),
-- (188, 'Fuchsias', '1 bush/shrub type pot max 6"/15cm'),
(19, 'Fuchsias', '1 bush/shrub type pot max 8"/20cm'),
-- (187, 'Fuchsias', '1 bush/shrub type pot max 8"/20cm'),
(18, 'Fuchsias', '1 double any size pot'),
(17, 'Fuchsias', '1 trailing any size pot'),
(93, 'Fun in the Snow', NULL),
(164, 'Garden Flower Arrangement', NULL),
(136, 'Garden in a Seed Tray 7/11', NULL),
(24, 'Geranium', '1 any size pot'),
(147, 'Gooseberries', NULL),
(80, 'Greetings Card', 'Age 3-6 Max Size A5'),
(81, 'Greetings Card', 'Age 7-11 Max Size A5'),
(77, 'Greetings Card', 'Max Size A5'),
(87, 'Hanging basket', '(max size 12"/30cm wire or plastic)'),
(192, 'Hanging basket', '(max size 12"/30cm)'),
(76, 'Hobby Exhibit', 'not included in any other class'),
(161, 'Hyacinths', NULL),
(162, 'Irises', NULL),
(206, 'Jar Chutney', '500g/1lb jar as specified'),
(150, 'Jar Jam', NULL),
(200, 'Jar Jam', '1lb/500g jar as specified'),
(165, 'Jar Marmalade', NULL),
(145, 'Knitting', NULL),
(71, 'Knitting/crochet', 'state if own design'),
(144, 'Lace', NULL),
(36, 'Lettuce (cabbage)', '2'),
(37, 'Lettuce (other)', '2'),
(149, 'Miniature', NULL),
(89, 'Monochrome', 'exhibit using flowers of one colour'),
(211, 'My Favourite Flower', NULL),
(167, 'Olympic Theme', NULL),
(195, 'One Vegetable and One Flower', NULL),
(218, 'Onions', '3 grown from sets'),
(39, 'Onions (grown from sets)', '6'),
(178, 'Onions 3', NULL),
(84, 'Painted Stone', 'Age 3-6'),
(3, 'Pansies', '4 blooms'),
(21, 'Patio Pot', '12"/30cm across, any type, any shape'),
(189, 'Patio Pot', 'in any size pot'),
(40, 'Peas', '6 pods'),
(210, 'Pests in the Garden', NULL),
(140, 'Photo of my Pet', NULL),
(214, 'Photo of my Pet', 'unmounted'),
(4, 'Pinks', '4 blooms'),
(175, 'Plant(s) Grown from Seed', NULL),
(217, 'Plant(s) Grown from Seed', 'In any size pot'),
(163, 'Pot Alpine', NULL),
(123, 'Pot Any Bulb', NULL),
(122, 'Pot Daffs/Narc', NULL),
(126, 'Pot Foliage', NULL),
(226, 'Pot of Tulips', NULL),
(227, 'Pot of Tulips', NULL),
(125, 'Pot Primula', NULL),
(128, 'Pot Succulents/Cacti', NULL),
(220, 'Potatoes', '3 of any one variety'),
(41, 'Potatoes', '5 of any variety'),
(177, 'Potatoes 3', NULL),
(181, 'Potatoes 3 (3-6y)', NULL),
(168, 'Queens Diamond Jubilee', NULL),
(32, 'Radishes', '5 untrimmed'),
(52, 'Raspberries', '6 with calyx'),
(51, 'Redcurrants', '3 strings'),
(23, 'Regal Pelargonium', '1 any size pot'),
(45, 'Rhubarb', '5 sticks minus leaves'),
(186, 'Roses', '1 specimen type'),
(8, 'Roses', '3 blooms H.T. of one cultivar'),
(9, 'Roses', '3 blooms H.T. of two or more cultivars'),
(10, 'Roses', '3 stems floribunda type'),
(11, 'Roses', 'one specimen type'),
(154, 'Savoury Quiche', NULL),
(204, 'Savoury Quiche or Flan', 'not exceeding 8"/20cm diameter'),
(60, 'Scones (plain)', '5'),
(43, 'Shallots (over 30mm)', '9'),
(42, 'Shallots (under 30mm)', '9'),
(184, 'Small Flowers', '6 blooms (not to exceed size of Â£2 coin)'),
(5, 'Small Flowers', '6 blooms (not to sxceed size of ?2 coin)'),
(139, 'Small Vase of Flowers 7/11', NULL),
(116, 'Society Bulb', NULL),
(148, 'Somewhere over the rainbow', NULL),
(228, 'Special Class', NULL),
(229, 'Special Class', NULL),
(120, 'Spring Flowers', NULL),
(38, 'Spring Onions', '6 untrimmed'),
(72, 'Still Life', 'Any Medium'),
(53, 'Strawberries', '6 with calyx'),
(27, 'Succulents or cacti', 'in any size pot'),
(172, 'Sunrise/Sunset', NULL),
(183, 'Sweet Peas', '3 x one cultivar'),
(1, 'Sweet Peas', '3 x one cultivars'),
(2, 'Sweet Peas', '6 x two or more cultivars'),
(198, 'Table decoration for a Celebration', NULL),
(92, 'Textures', NULL),
(208, 'The Four Seasons', 'A series of Four photographs'),
(46, 'Tomatoes', '3 with calyx'),
(91, 'Transport', NULL),
(94, 'Trees/Shrubs in Flower', NULL),
(224, 'Turnips', '2 trimmed to 7.5cm/3"'),
(49, 'Two different fresh culinary herbs', '1 vase max 3"/7.5cm diam'),
-- (196, 'Two different fresh culinary herbs', '1 vase max 3"/7.5cm diam'),
-- (225, 'Two Different fresh Culinary herbs', '1 vase max 7.5cm/3" diam'),
(130, 'Vase of annuals', NULL),
(131, 'Vase of any other flowers', NULL),
(61, 'Victoria Jam Sandwich', '7.5"/18cm diameter approx'),
(201, 'Victoria Jam Sandwich', '7.5"/19cm diameter approx'),
(65, 'Water', NULL),
(207, 'White Bread Rolls', '6'),
(158, 'Winter Colour in the Garden', NULL),
(68, 'Winter Scene', NULL),
(67, 'Young Animals or Birds', 'eg. puppies, kittens');


